# SNAP Makefile Configuration (from snap/makefile.config)

GLIB = glib-core
SNAP = snap-core
GLIBADV = glib-adv
SNAPADV = snap-adv
SNAPEXP = snap-exp

CGLIB = snap/$(GLIB)
CSNAP = snap/$(SNAP)

# Compile support for Linux only.
CC = g++
CXXFLAGS += -std=c++11 -Wall -DNDEBUG -O3
# turn on for crash debugging, get symbols with <prog> 2>&1 | c++filt
#CXXFLAGS += -g -rdynamic
CXXOPENMP = -fopenmp
LIBS += -lrt -lm
